### ISSUE TITLE
onNoteOff event triggers onNoteOn in example 

### ISSUE THREAD

**Issue by VorkHeftruck** [pschatzmann/arduino-midi#2]
In the Ble-receive example an incoming noteOff is interpreted as a noteOn event resulting in only noteOn events.
I haven't changed anything in the example code and I'm quite positive an noteOff is send to the Ble server.

**Comment by pschatzmann** [comment]
I have tested this with PocketMidi.
I suggest that you try if you can reproduce this with some other way (software) that generates midi messages.
You can also activate the log to see which methods are called
MidiLogLevel= MidiInfo; // or MidiDebug

**Comment by VorkHeftruck** [comment]
Ahhh! Nice catch. Thank you for the update!
